name: hardwaresimu_software_graduation_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  firebase_core: ^3.12.1
  image_picker: ^1.1.2
  firebase_auth: ^5.5.2
  google_sign_in: ^6.2.2
  provider: ^6.1.4
  web_smooth_scroll: ^2.0.0
  carousel_slider: ^5.0.0
  dots_indicator: ^4.0.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  http: ^1.3.0
  intl: ^0.20.2
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.7.0
  cloud_firestore: ^5.6.7
  chewie: ^1.11.3
  video_player: ^2.9.5
  flutter_facebook_auth: ^7.1.2
  flutter_web_auth_2: ^4.1.0
  file_picker: ^10.1.7
  supabase_flutter: ^2.9.0
  go_router: ^15.1.2
  fl_chart: ^1.0.0
  url_launcher: ^6.3.1
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  videosdk: ^2.2.0
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1
  # dio: ^5.8.0+1
  # path_provider: ^2.1.5
  # web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 


flutter:
  assets:
    - Images/
  uses-material-design: true
