// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVAWEgpCgOIgbdCi8vovdeL0BV2LyE_uc',
    appId: '1:899180293396:web:a8210d1fbab99c4bace601',
    messagingSenderId: '899180293396',
    projectId: 'testfire-b75ce',
    authDomain: 'testfire-b75ce.firebaseapp.com',
    storageBucket: 'testfire-b75ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_X97alAPOQBZDgPjQEmHAYOrQXpQ3wlU',
    appId: '1:899180293396:android:94754f9163e9fdd0ace601',
    messagingSenderId: '899180293396',
    projectId: 'testfire-b75ce',
    storageBucket: 'testfire-b75ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHLlJZ5x0IQdKxbTIk8M-VEBpPJjeuYZA',
    appId: '1:899180293396:ios:b61090ba46ceef63ace601',
    messagingSenderId: '899180293396',
    projectId: 'testfire-b75ce',
    storageBucket: 'testfire-b75ce.firebasestorage.app',
    iosBundleId: 'com.example.hardwaresimuSoftwareGraduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHLlJZ5x0IQdKxbTIk8M-VEBpPJjeuYZA',
    appId: '1:899180293396:ios:b61090ba46ceef63ace601',
    messagingSenderId: '899180293396',
    projectId: 'testfire-b75ce',
    storageBucket: 'testfire-b75ce.firebasestorage.app',
    iosBundleId: 'com.example.hardwaresimuSoftwareGraduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVAWEgpCgOIgbdCi8vovdeL0BV2LyE_uc',
    appId: '1:899180293396:web:853ddc2daf67954cace601',
    messagingSenderId: '899180293396',
    projectId: 'testfire-b75ce',
    authDomain: 'testfire-b75ce.firebaseapp.com',
    storageBucket: 'testfire-b75ce.firebasestorage.app',
  );
}
